### ISSUE TITLE
Saved_Model conversion for YOLOv4 does not create the variables files

### ISSUE THREAD

**Issue by arsenal-2004** [PINTO0309/openvino2tensorflow#11]
Hey @PINTO0309 
I have been trying to convert a pretrained YOLOv4 model from OpenVINO to TF Saved_Model. I earlier used your tool to convert other models like OSNet, which have worked perfectly. However, this time, the Saved_Model folder does not contain any variable files, which then causes an issue when I try to convert the Saved_Model to a TFLite format.
I get the following error. It's quite long and I apologise in advance for that. I have made it shorter by removing the Model description printed.
```
[setupvars.sh] OpenVINO environment initialized
TensorFlow/Keras model building process starts ======================================
/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py:22: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
.....
__________________________________________________________________________________________________
TensorFlow/Keras model building process complete!
saved_model output started ==========================================================
ERROR: can't pickle module objects
Traceback (most recent call last):
  File "/usr/local/bin/openvino2tensorflow", line 1676, in convert
    tf.saved_model.save(model, model_output_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 1033, in save
    obj, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 1198, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 1163, in _build_meta_graph_impl
    asset_info.asset_index)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 755, in _serialize_object_graph
    saveable_view.function_name_map)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/save.py", line 800, in _write_object_proto
    metadata=obj._tracking_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 3079, in _tracking_metadata
    return self._trackable_saved_model_saver.tracking_metadata
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 55, in tracking_metadata
    return json_utils.Encoder().encode(self.python_properties)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 41, in python_properties
    return self._python_properties_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 35, in _python_properties_internal
    metadata = super(ModelSavedModelSaver, self)._python_properties_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 59, in _python_properties_internal
    metadata.update(get_config(self.obj))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 118, in get_config
    config = generic_utils.serialize_keras_object(obj)['config']
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py", line 245, in serialize_keras_object
    config = instance.get_config()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 650, in get_config
    return copy.deepcopy(get_network_config(self))
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle module objects
Switch to the output of an optimized protocol buffer file (.pb).
.pb output started ==================================================================
.pb output complete! - /content/drive/MyDrive/Clutterbot/YOLO/yolov4_crowdhuman_saved_model/model_float32.pb
WARNING:tensorflow:From /usr/local/bin/openvino2tensorflow:1759: simple_save (from tensorflow.python.saved_model.simple_save) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.simple_save.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/signature_def_utils_impl.py:201: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
Optimized graph converted to SavedModel! - /content/drive/MyDrive/Clutterbot/YOLO/yolov4_crowdhuman_saved_model
All the conversion process is finished! =============================================
```

Could you please help me with this?

The XML and BIN files of the OpenVINO IR are [here](https://drive.google.com/file/d/1GZA6vdWKLcQJWNfUepNEk_Lzsd62vTML/view?usp=sharing), [here](https://drive.google.com/file/d/1quRakHiOSdNKJPuxjOpf2ZFCJWxkNFYt/view?usp=sharing)

**Comment by PINTO0309** [comment]
No problem. It is possible to convert to tflite without variable files.

Please use the following command script.
**https://github.com/PINTO0309/openvino2tensorflow#5-2-saved_model-to-tflite-convert**

example:
```
$ saved_model_to_tflite \
--saved_model_dir_path saved_model \
--output_no_quant_float32_tflite True
```

**Comment by arsenal-2004** [comment]
@PINTO0309 That worked. Thank you so much. Any reason for the variable files being missing in the first place?

**Comment by PINTO0309** [comment]
1. An error occurs when the size of a pickle object exceeds 2GB.
2. My program detects the error internally and automatically performs a recovery operation to generate a .pb file in v1 format.
3. Automatically generate saved_model from .pb in v1 format
4. A saved_model generated from a v1 format .pb file will be in v1 format saved_model format and will be generated without any variable files.
5. The structure of the final generated saved_model in v1 format is essentially the same as that of the saved_model in v2 format.

**Comment by arsenal-2004** [comment]
Oh okay. I understand. Thank you :)
