### ISSUE TITLE
Error in Conversion /openvino to tensorflow

### ISSUE THREAD

**Issue by NaeemKhan333** [PINTO0309/openvino2tensorflow#14]
@PINTO0309 Thanks for nice work . I am trying to convert u2net model to tensorflow Js .I have done all the above given steps but while I run the following command .I am getting following error.

-> Working on Ubuntu operating System
-> Working on CPU Device

$ openvino2tensorflow --model_path openvino/320x320/FP32/u2netp_320x320.xml --model_output_path saved_model_320x320 --output_saved_model True
Traceback (most recent call last):
  File "/home/user/anaconda3/bin/openvino2tensorflow", line 66, in <module>
    from openvino.inference_engine import IECore
  File "/home/user/anaconda3/lib/python3.7/site-packages/openvino/inference_engine/__init__.py", line 1, in <module>
    from .ie_api import *
ImportError: /home/user/anaconda3/bin/../lib/libinference_engine.so: undefined symbol: _ZN3tbb8internal13numa_topology4fillEPi

**Comment by PINTO0309** [comment]
It seems that your Anaconda environment is not recognizing TBB correctly. We recommend you try it without Anaconda.

1. https://github.com/openvinotoolkit/openvino/issues/3929

2. https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/ImportError-undefined-symbol-ZN3tbb8internal13numa/td-p/1169149

**Comment by NaeemKhan333** [comment]
@PINTO0309 Thank you . I am not facing the above issue by using without conda environment.But I am facing following issue

The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/user/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
Traceback (most recent call last):
  File "/home/user/.local/bin/openvino2tensorflow", line 2131, in <module>
    main()
  File "/home/user/.local/bin/openvino2tensorflow", line 2127, in main
    yolact, debug, debug_layer_number)
  File "/home/user/.local/bin/openvino2tensorflow", line 1663, in convert
    tf_layers_dict[layer_id] = tf.identity(tf_layers_dict[get_tf_edges_from(tf_edges, layer_id, 0)], name=layer.attrib['name'].split('/')[0])
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 287, in identity
    ret = gen_array_ops.identity(input, name=name)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4002, in identity
    "Identity", input=input, name=name)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 353, in _apply_op_helper
    with g.as_default(), ops.name_scope(name) as scope:
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6492, in __enter__
    return self._name_scope.__enter__()
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4190, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: 'F.sigmoid(d0)' is not a valid scope name

Can You Guide me About It .Thanks

**Comment by NaeemKhan333** [comment]
I solved the above mentioned issue by modifying the command which I run for converting the onnx model format

Facing Error while running the following command:

python3 /home/user/intel/openvino_2021.2.185/deployment_tools/tools/model_downloader/pytorch_to_onnx.py --import-module model.u2net --model-name U2NETP --input-shape 1,3,320,320 --weights saved_models/u2netp/u2netp.pth --output-file u2netp_320x320.onnx --input-names "x" --output-names "F.sigmoid(d0),F.sigmoid(d1),F.sigmoid(d2),F.sigmoid(d3),F.sigmoid(d4),F.sigmoid(d5),F.sigmoid(d6)"

Change the Command:

python3 /home/user/intel/openvino_2021/deployment_tools/tools/model_downloader/pytorch_to_onnx.py --import-module model.u2net --model-name U2NETP --input-shape 1,3,320,320 --weights saved_models/u2netp/u2netp.pth --output-file u2netp_320x320.onnx --input-names "x" --output-names "a/F.sigmoid(d0)"

This resolve the above highlighted error and I done conversion successfully by using your blog.Thanks
