### ISSUE TITLE
TypeError: cannot pickle 'module' object

### ISSUE THREAD

**Issue by Mukulareddy** [PINTO0309/openvino2tensorflow#144]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

OpenVINO

### Download URL for ONNX / OpenVINO IR

https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_tiny_openvino.tar.gz

### Convert Script

python openvino2tensorflow.py --model_path /yolox_tiny_sim.xml --model_output_path saved_h5_416_416 --output_h5

### Description

When i tried converting the OpenVINO IR format of the  model to .h5 model using the above command I am facing the below issue.
**TypeError: cannot pickle 'module' object**
It would be great if someone could help me with this.

### Relevant Log Output

```shell
layer_type: Const
layer_id: 453
tf_layers_dict_shape: (1, 96, 1, 1)
tf_layers_dict_value: [[[[ 2.3701844 ]]

  [[ 1.9270271 ]]

  [[ 1.1629344 ]]

  [[-0.13331127]]

  [[ 1.1646254 ]]

  [[ 1.6272382 ]]

  [[ 2.0330715 ]]

  [[ 2.4103541 ]]

  [[ 1.1794468 ]]

  [[ 3.1922562 ]]

  [[ 0.80192804]]

  [[ 0.918452  ]]

  [[ 1.6562974 ]]

  [[ 0.8284194 ]]

  [[ 1.5944452 ]]

  [[-0.43591785]]

  [[ 1.4425404 ]]

  [[-2.1579928 ]]

  [[ 2.5115259 ]]

  [[ 0.10604887]]

  [[ 0.53013325]]

  [[ 2.4593568 ]]

  [[ 3.8425333 ]]

  [[ 1.510612  ]]

  [[ 2.6186988 ]]

  [[-0.365788  ]]

  [[-0.07304868]]

  [[ 1.9684379 ]]

  [[ 1.0933251 ]]

  [[ 0.34470552]]

  [[ 1.1178714 ]]

  [[ 3.5374014 ]]

  [[ 2.1186767 ]]

  [[ 0.66732824]]

  [[ 1.0683035 ]]

  [[ 2.7602077 ]]

  [[ 3.2852457 ]]

  [[-0.38651127]]

  [[ 1.9059887 ]]

  [[ 1.5833094 ]]

  [[ 1.889504  ]]

  [[ 0.8861643 ]]

  [[ 1.2405196 ]]

  [[ 1.3878361 ]]

  [[ 1.956938  ]]

  [[ 1.8078754 ]]

  [[ 1.3849156 ]]

  [[ 3.4051569 ]]

  [[ 3.1490602 ]]

  [[-1.0523298 ]]

  [[ 1.1143126 ]]

  [[ 0.8821161 ]]

  [[-0.2029241 ]]

  [[ 1.4012253 ]]

  [[ 1.7876036 ]]

  [[-2.3801851 ]]

  [[ 1.4638995 ]]

  [[ 0.89194554]]

  [[-0.9520595 ]]

  [[ 1.6488714 ]]

  [[ 0.8080565 ]]

  [[ 1.416472  ]]

  [[ 1.9556634 ]]

  [[-0.6152393 ]]

  [[-2.6198537 ]]

  [[ 1.3389992 ]]

  [[ 0.62451863]]

  [[-1.3831    ]]

  [[ 2.601157  ]]

  [[ 4.2489877 ]]

  [[ 0.956818  ]]

  [[ 1.4448963 ]]

  [[ 1.2242935 ]]

  [[ 1.7796409 ]]

  [[ 1.0258006 ]]

  [[-2.1094725 ]]

  [[-0.2001234 ]]

  [[-0.27974838]]

  [[ 1.2242429 ]]

  [[-0.8142648 ]]

  [[ 0.9820821 ]]

  [[ 1.9820187 ]]

  [[ 1.4535207 ]]

  [[ 3.1459603 ]]

  [[ 0.8010211 ]]

  [[ 3.373296  ]]

  [[ 2.507955  ]]

  [[ 2.4872022 ]]

  [[ 1.7825925 ]]

  [[-1.1367719 ]]

  [[ 0.3731116 ]]

  [[ 1.4726274 ]]

  [[-0.5747317 ]]

  [[ 1.4636103 ]]

  [[ 1.4617355 ]]

  [[ 1.5335329 ]]]]
====================================================================================
layer_type: Add
layer_id: 454
input_layer0: layer_id=452: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 96), dtype=tf.float32, name=None), name='conv2d_81/Conv2D:0', description="created by layer 'conv2d_81'")
input_layer1_value: layer_id=453: [[[[ 2.3701844 ]]

  [[ 1.9270271 ]]

  [[ 1.1629344 ]]

  [[-0.13331127]]

  [[ 1.1646254 ]]

  [[ 1.6272382 ]]

  [[ 2.0330715 ]]

  [[ 2.4103541 ]]

  [[ 1.1794468 ]]

  [[ 3.1922562 ]]

  [[ 0.80192804]]

  [[ 0.918452  ]]

  [[ 1.6562974 ]]

  [[ 0.8284194 ]]

  [[ 1.5944452 ]]

  [[-0.43591785]]

  [[ 1.4425404 ]]

  [[-2.1579928 ]]

  [[ 2.5115259 ]]

  [[ 0.10604887]]

  [[ 0.53013325]]

  [[ 2.4593568 ]]

  [[ 3.8425333 ]]

  [[ 1.510612  ]]

  [[ 2.6186988 ]]

  [[-0.365788  ]]

  [[-0.07304868]]

  [[ 1.9684379 ]]

  [[ 1.0933251 ]]

  [[ 0.34470552]]

  [[ 1.1178714 ]]

  [[ 3.5374014 ]]

  [[ 2.1186767 ]]

  [[ 0.66732824]]

  [[ 1.0683035 ]]

  [[ 2.7602077 ]]

  [[ 3.2852457 ]]

  [[-0.38651127]]

  [[ 1.9059887 ]]

  [[ 1.5833094 ]]

  [[ 1.889504  ]]

  [[ 0.8861643 ]]

  [[ 1.2405196 ]]

  [[ 1.3878361 ]]

  [[ 1.956938  ]]

  [[ 1.8078754 ]]

  [[ 1.3849156 ]]

  [[ 3.4051569 ]]

  [[ 3.1490602 ]]

  [[-1.0523298 ]]

  [[ 1.1143126 ]]

  [[ 0.8821161 ]]

  [[-0.2029241 ]]

  [[ 1.4012253 ]]

  [[ 1.7876036 ]]

  [[-2.3801851 ]]

  [[ 1.4638995 ]]

  [[ 0.89194554]]

  [[-0.9520595 ]]

  [[ 1.6488714 ]]

  [[ 0.8080565 ]]

  [[ 1.416472  ]]

  [[ 1.9556634 ]]

  [[-0.6152393 ]]

  [[-2.6198537 ]]

  [[ 1.3389992 ]]

  [[ 0.62451863]]

  [[-1.3831    ]]

  [[ 2.601157  ]]

  [[ 4.2489877 ]]

  [[ 0.956818  ]]

  [[ 1.4448963 ]]

  [[ 1.2242935 ]]

  [[ 1.7796409 ]]

  [[ 1.0258006 ]]

  [[-2.1094725 ]]

  [[-0.2001234 ]]

  [[-0.27974838]]

  [[ 1.2242429 ]]

  [[-0.8142648 ]]

  [[ 0.9820821 ]]

  [[ 1.9820187 ]]

  [[ 1.4535207 ]]

  [[ 3.1459603 ]]

  [[ 0.8010211 ]]

  [[ 3.373296  ]]

  [[ 2.507955  ]]

  [[ 2.4872022 ]]

  [[ 1.7825925 ]]

  [[-1.1367719 ]]

  [[ 0.3731116 ]]

  [[ 1.4726274 ]]

  [[-0.5747317 ]]

  [[ 1.4636103 ]]

  [[ 1.4617355 ]]

  [[ 1.5335329 ]]]]
tf_layers_dict: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 96), dtype=tf.float32, name=None), name='tf.math.add_88/Add:0', description="created by layer 'tf.math.add_88'")
====================================================================================
layer_type: Swish
layer_id: 455
input_layer0: layer_id=454: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 96), dtype=tf.float32, name=None), name='tf.math.add_88/Add:0', description="created by layer 'tf.math.add_88'")
tf_layers_dict: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 96), dtype=tf.float32, name=None), name='tf.nn.silu_73/IdentityN:0', description="created by layer 'tf.nn.silu_73'")
====================================================================================
layer_type: Const
layer_id: 456
tf_layers_dict_shape: (80, 96, 1, 1)
tf_layers_dict_value: [[[[-0.00134261]]

  [[ 0.02483658]]

  [[ 0.01132369]]

  ...

  [[ 0.05432326]]

  [[ 0.02210934]]

  [[-0.10504632]]]


 [[[ 0.01528567]]

  [[-0.04844463]]

  [[ 0.0257682 ]]

  ...

  [[ 0.04475677]]

  [[-0.04777099]]

  [[-0.05116702]]]


 [[[ 0.06951346]]

  [[-0.0500924 ]]

  [[ 0.01201853]]

  ...

  [[ 0.03735595]]

  [[ 0.06382217]]

  [[ 0.06946969]]]


 ...


 [[[-0.02434462]]

  [[-0.01090814]]

  [[-0.04184687]]

  ...

  [[ 0.02591012]]

  [[-0.04448308]]

  [[-0.02062458]]]


 [[[-0.01642143]]

  [[-0.01935942]]

  [[-0.0281077 ]]

  ...

  [[-0.02653849]]

  [[-0.02628284]]

  [[-0.02066284]]]


 [[[-0.0185364 ]]

  [[-0.00245801]]

  [[-0.03015505]]

  ...

  [[-0.02596138]]

  [[-0.03245317]]

  [[-0.01943119]]]]
====================================================================================
layer_type: Convolution
layer_id: 457
input_layer0: layer_id=455: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 96), dtype=tf.float32, name=None), name='tf.nn.silu_73/IdentityN:0', description="created by layer 'tf.nn.silu_73'")
input_layer1_value: layer_id=456: [[[[-0.00134261]]

  [[ 0.02483658]]

  [[ 0.01132369]]

  ...

  [[ 0.05432326]]

  [[ 0.02210934]]

  [[-0.10504632]]]


 [[[ 0.01528567]]

  [[-0.04844463]]

  [[ 0.0257682 ]]

  ...

  [[ 0.04475677]]

  [[-0.04777099]]

  [[-0.05116702]]]


 [[[ 0.06951346]]

  [[-0.0500924 ]]

  [[ 0.01201853]]

  ...

  [[ 0.03735595]]

  [[ 0.06382217]]

  [[ 0.06946969]]]


 ...


 [[[-0.02434462]]

  [[-0.01090814]]

  [[-0.04184687]]

  ...

  [[ 0.02591012]]

  [[-0.04448308]]

  [[-0.02062458]]]


 [[[-0.01642143]]

  [[-0.01935942]]

  [[-0.0281077 ]]

  ...

  [[-0.02653849]]

  [[-0.02628284]]

  [[-0.02066284]]]


 [[[-0.0185364 ]]

  [[-0.00245801]]

  [[-0.03015505]]

  ...

  [[-0.02596138]]

  [[-0.03245317]]

  [[-0.01943119]]]]
tf_layers_dict: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 80), dtype=tf.float32, name=None), name='conv2d_82/Conv2D:0', description="created by layer 'conv2d_82'")
====================================================================================
layer_type: Const
layer_id: 458
tf_layers_dict_shape: (1, 80, 1, 1)
tf_layers_dict_value: [[[[-3.0110283]]

  [[-4.6342773]]

  [[-4.209836 ]]

  [[-4.5913563]]

  [[-4.3242917]]

  [[-4.577049 ]]

  [[-4.11077  ]]

  [[-4.2169895]]

  [[-4.38152  ]]

  [[-4.8655734]]

  [[-4.770194 ]]

  [[-4.879881 ]]

  [[-4.8631897]]

  [[-4.050074 ]]

  [[-4.5508194]]

  [[-4.6962743]]

  [[-4.732042 ]]

  [[-4.658122 ]]

  [[-4.57228  ]]

  [[-4.7797318]]

  [[-4.6175857]]

  [[-4.8918033]]

  [[-4.8631897]]

  [[-4.5341277]]

  [[-4.8774962]]

  [[-4.3076005]]

  [[-4.8822656]]

  [[-4.825037 ]]

  [[-4.5555887]]

  [[-4.9371085]]

  [[-4.7845006]]

  [[-4.817884 ]]

  [[-4.9681077]]

  [[-4.5889716]]

  [[-4.8608046]]

  [[-4.9204173]]

  [[-4.7964234]]

  [[-4.6152015]]

  [[-4.7964234]]

  [[-4.81073  ]]

  [[-4.863189 ]]

  [[-4.867958 ]]

  [[-4.8870344]]

  [[-4.898957 ]]

  [[-4.9347243]]

  [[-4.7034273]]

  [[-4.631893 ]]

  [[-4.853651 ]]

  [[-4.977645 ]]

  [[-4.827422 ]]

  [[-4.960954 ]]

  [[-4.9379005]]

  [[-4.8918033]]

  [[-4.827422 ]]

  [[-4.957451 ]]

  [[-4.717735 ]]

  [[-4.3600593]]

  [[-4.119225 ]]

  [[-4.391058 ]]

  [[-4.131644 ]]

  [[-3.1292489]]

  [[-4.52459  ]]

  [[-4.4935913]]

  [[-4.608048 ]]

  [[-5.0134125]]

  [[-4.8154993]]

  [[-4.6605067]]

  [[-4.7916546]]

  [[-4.851267 ]]

  [[-4.505514 ]]

  [[-4.9824147]]

  [[-4.6557374]]

  [[-4.391058 ]]

  [[-4.632957 ]]

  [[-4.803577 ]]

  [[-4.844113 ]]

  [[-4.8488827]]

  [[-4.832191 ]]

  [[-4.999106 ]]

  [[-4.944262 ]]]]
====================================================================================
layer_type: Add
layer_id: 459
input_layer0: layer_id=457: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 80), dtype=tf.float32, name=None), name='conv2d_82/Conv2D:0', description="created by layer 'conv2d_82'")
input_layer1_value: layer_id=458: [[[[-3.0110283]]

  [[-4.6342773]]

  [[-4.209836 ]]

  [[-4.5913563]]

  [[-4.3242917]]

  [[-4.577049 ]]

  [[-4.11077  ]]

  [[-4.2169895]]

  [[-4.38152  ]]

  [[-4.8655734]]

  [[-4.770194 ]]

  [[-4.879881 ]]

  [[-4.8631897]]

  [[-4.050074 ]]

  [[-4.5508194]]

  [[-4.6962743]]

  [[-4.732042 ]]

  [[-4.658122 ]]

  [[-4.57228  ]]

  [[-4.7797318]]

  [[-4.6175857]]

  [[-4.8918033]]

  [[-4.8631897]]

  [[-4.5341277]]

  [[-4.8774962]]

  [[-4.3076005]]

  [[-4.8822656]]

  [[-4.825037 ]]

  [[-4.5555887]]

  [[-4.9371085]]

  [[-4.7845006]]

  [[-4.817884 ]]

  [[-4.9681077]]

  [[-4.5889716]]

  [[-4.8608046]]

  [[-4.9204173]]

  [[-4.7964234]]

  [[-4.6152015]]

  [[-4.7964234]]

  [[-4.81073  ]]

  [[-4.863189 ]]

  [[-4.867958 ]]

  [[-4.8870344]]

  [[-4.898957 ]]

  [[-4.9347243]]

  [[-4.7034273]]

  [[-4.631893 ]]

  [[-4.853651 ]]

  [[-4.977645 ]]

  [[-4.827422 ]]

  [[-4.960954 ]]

  [[-4.9379005]]

  [[-4.8918033]]

  [[-4.827422 ]]

  [[-4.957451 ]]

  [[-4.717735 ]]

  [[-4.3600593]]

  [[-4.119225 ]]

  [[-4.391058 ]]

  [[-4.131644 ]]

  [[-3.1292489]]

  [[-4.52459  ]]

  [[-4.4935913]]

  [[-4.608048 ]]

  [[-5.0134125]]

  [[-4.8154993]]

  [[-4.6605067]]

  [[-4.7916546]]

  [[-4.851267 ]]

  [[-4.505514 ]]

  [[-4.9824147]]

  [[-4.6557374]]

  [[-4.391058 ]]

  [[-4.632957 ]]

  [[-4.803577 ]]

  [[-4.844113 ]]

  [[-4.8488827]]

  [[-4.832191 ]]

  [[-4.999106 ]]

  [[-4.944262 ]]]]
tf_layers_dict: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 80), dtype=tf.float32, name=None), name='tf.math.add_89/Add:0', description="created by layer 'tf.math.add_89'")
====================================================================================
layer_type: Sigmoid
layer_id: 460
input_layer0: layer_id=459: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 80), dtype=tf.float32, name=None), name='tf.math.add_89/Add:0', description="created by layer 'tf.math.add_89'")
tf_layers_dict: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 80), dtype=tf.float32, name=None), name='tf.math.sigmoid_5/Sigmoid:0', description="created by layer 'tf.math.sigmoid_5'")
====================================================================================
layer_type: Concat
layer_id: 461
input_layer0: layer_id=440: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 4), dtype=tf.float32, name=None), name='tf.math.add_85/Add:0', description="created by layer 'tf.math.add_85'")
input_layer1: layer_id=445: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 1), dtype=tf.float32, name=None), name='tf.math.sigmoid_4/Sigmoid:0', description="created by layer 'tf.math.sigmoid_4'")
input_layer2: layer_id=460: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 80), dtype=tf.float32, name=None), name='tf.math.sigmoid_5/Sigmoid:0', description="created by layer 'tf.math.sigmoid_5'")
tf_layers_dict: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 85), dtype=tf.float32, name=None), name='tf.concat_16/concat:0', description="created by layer 'tf.concat_16'")
axis: -1
====================================================================================
layer_type: Reshape
layer_id: 462
input_layer0: layer_id=461: KerasTensor(type_spec=TensorSpec(shape=(1, 13, 13, 85), dtype=tf.float32, name=None), name='tf.concat_16/concat:0', description="created by layer 'tf.concat_16'")
input_layer1_value: layer_id=315: [ 1 85 -1]
tf_layers_dict: KerasTensor(type_spec=TensorSpec(shape=(1, 169, 85), dtype=tf.float32, name=None), name='tf.reshape_2/Reshape:0', description="created by layer 'tf.reshape_2'")
====================================================================================
layer_type: Concat
layer_id: 463
input_layer0: layer_id=316: KerasTensor(type_spec=TensorSpec(shape=(1, 2704, 85), dtype=tf.float32, name=None), name='tf.reshape/Reshape:0', description="created by layer 'tf.reshape'")
input_layer1: layer_id=389: KerasTensor(type_spec=TensorSpec(shape=(1, 676, 85), dtype=tf.float32, name=None), name='tf.reshape_1/Reshape:0', description="created by layer 'tf.reshape_1'")
input_layer2: layer_id=462: KerasTensor(type_spec=TensorSpec(shape=(1, 169, 85), dtype=tf.float32, name=None), name='tf.reshape_2/Reshape:0', description="created by layer 'tf.reshape_2'")
tf_layers_dict: KerasTensor(type_spec=TensorSpec(shape=(1, 3549, 85), dtype=tf.float32, name=None), name='tf.concat_17/concat:0', description="created by layer 'tf.concat_17'")
axis: 1
====================================================================================
layer_type: Const
layer_id: 464
tf_layers_dict_shape: (3,)
tf_layers_dict_value: [0 2 1]
====================================================================================
layer_type: Transpose
layer_id: 465
input_layer0: layer_id=463: KerasTensor(type_spec=TensorSpec(shape=(1, 3549, 85), dtype=tf.float32, name=None), name='tf.concat_17/concat:0', description="created by layer 'tf.concat_17'")
input_layer1_value: layer_id=464: [0 2 1]
tf_layers_dict: KerasTensor(type_spec=TensorSpec(shape=(1, 85, 3549), dtype=tf.float32, name=None), name='tf.compat.v1.transpose/transpose:0', description="created by layer 'tf.compat.v1.transpose'")
====================================================================================
layer_type: Result
layer_id: 466
input_layer0: layer_id=465: KerasTensor(type_spec=TensorSpec(shape=(1, 85, 3549), dtype=tf.float32, name=None), name='tf.compat.v1.transpose/transpose:0', description="created by layer 'tf.compat.v1.transpose'")
tf_layers_dict: KerasTensor(type_spec=TensorSpec(shape=(1, 85, 3549), dtype=tf.float32, name=None), name='tf.identity/Identity:0', description="created by layer 'tf.identity'")
====================================================================================
TensorFlow/Keras model building process complete!
.h5 output started ==================================================================
ERROR: cannot pickle 'module' object
Traceback (most recent call last):
  File "/hdd/mukula_STS/SOW6.4/october/openvino2tensorflow/openvino2tensorflow/openvino2tensorflow.py", line 7149, in convert
    model.save(f'{model_output_path}/model_float32.h5', include_optimizer=False, save_format='h5')
  File "/home/user1/envs/py39/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 296, in _reconstruct
    value = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.9/copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.9/copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'module' object
All the conversion process is finished! =============================================
```

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/onnx2tf
