### ISSUE TITLE
Segmentation map is different after conversion

### ISSUE THREAD

**Issue by bmmlover** [PINTO0309/openvino2tensorflow#18]
Hi!
I'm trying to convert BiSeNet from PyTorch to TFLite (PyTorch -> ONNX -> OpenVino -> TF). I followed steps from your [article](https://qiita.com/PINTO/items/ed06e03eb5c007c2e102), except conversion to ONNX. For PyTorch -> ONNX conversion I used
```
torch_out = torch.onnx._export(net, dummy_nhwc, "bisenet.onnx", export_params=True,
                               input_names=['input'],  output_names=['output'], opset_version=11)
```
When I use pytorch_to_onnx.py from openvino, I get following error:
```
UserWarning: ONNX export failed on upsample_bilinear2d because align_corners == True not supported
RuntimeError: ONNX export failed: Couldn't export operator aten::upsample_bilinear2d
```

After conversion to tflite output segmentation map differs from output of pytorch and onnx model.

Output of onnx:
![seg_onnx](https://user-images.githubusercontent.com/19303316/106165062-bd60e080-619b-11eb-8fad-e170249332ee.png)

Output of tflite:
![seg_tflite](https://user-images.githubusercontent.com/19303316/106165078-c2be2b00-619b-11eb-876e-f12b350c0cd5.png)

I tried to convert model with --output_edgetpu True and False (to resize with tf.compat.v1.image.resize_* and with tf.image.resize), but both tflite models produce same results. Any help would be appriciated!

Environment:
tf-nightly                    2.5.0.dev20210128
openvino2tensorflow           1.5.8

**Comment by PINTO0309** [comment]
I would like to verify this.

1. Is it possible to share the URL of the repository you used, or the PyTorch repository? If you have created your own model, it would be great if you could also provide me with the code for testing.
2. By the way, the model committed in the following URL is the face segmentation model of BiSeNetV2, does the problem still occur when using this model?
- **BiSeNetV2 (celebamaskhq)**
**https://github.com/PINTO0309/PINTO_model_zoo/tree/main/057_BiSeNetV2/02_celebamaskhq**

**Comment by bmmlover** [comment]
Thank you for reply,
1. I use model from https://github.com/zllrunning/face-parsing.PyTorch
2. Yes,
https://drive.google.com/file/d/1-84uVDUKEEcGdRFeorB7SMM_3J_jRO48/view?usp=sharing -- this is version before onnx simplifier,
https://drive.google.com/file/d/1aCFmd4fyGt2OKnBWnX9pS9cS8ZEIPmBC/view?usp=sharing -- after.
I also tried to skip onnx simplifier step to check if it affects final result, but nothing changed.
3. I tried to convert float32/saved_model_448x448/saved_model.pb to tflite, and problem didn't occur. Result is the same as after saved_model_448x448/model_float32.onnx. But I want to modify this pytorch model, so I need the way to convert pytorch models to tflite. I tried onnx-tensorflow before, but I need to convert model from NCHW to NHWC, and get rid of extra transposes.

I also tried to convert model from 07_openvino (FP32 256x256 and 448x448) to tflite, and convert model from float32 to openvino and then to tflite, and in all cases got following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/openvino2tensorflow", line 2201, in <module>
    main()
  File "/usr/local/bin/openvino2tensorflow", line 2197, in main
    yolact, debug, debug_layer_number)
  File "/usr/local/bin/openvino2tensorflow", line 577, in convert
    x_outputs = [conv(x_split) for x_split, conv in zip(x_splits, convs)]
  File "/usr/local/bin/openvino2tensorflow", line 577, in <listcomp>
    x_outputs = [conv(x_split) for x_split, conv in zip(x_splits, convs)]
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 972, in __call__
    input_list)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1111, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 841, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 881, in _infer_output_signature
    self._maybe_build(inputs)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2722, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py", line 205, in build
    dtype=self.dtype)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 655, in add_weight
    caching_device=caching_device)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 810, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 142, in make_variable
    shape=variable_shape if variable_shape else None)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 260, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 221, in _variable_v1_call
    shape=shape)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 199, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2624, in default_variable_creator
    shape=shape)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1586, in __init__
    distribute_strategy=distribute_strategy)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1713, in _init_from_args
    initial_value = initial_value()
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/keras/initializers/initializers_v2.py", line 237, in __call__
    self.value, dtype=_get_dtype(dtype), shape=shape)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 265, in constant
    allow_broadcast=True)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 276, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/home/masha/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 325, in _constant_eager_impl
    (num_t, shape, shape.num_elements()))
TypeError: Eager execution of tf.constant with unsupported shape (value has 54 elements, shape is (3, 3, 1, 1) with 9 elements).
```

**Comment by PINTO0309** [comment]
Thanks for the detailed explanation.
OK, I understand your intentions. Please give me some time to investigate.

**Comment by bmmlover** [comment]
Hi! I found out that this problem is caused by padding in Conv2D layer. I inserted ZeroPadding2D before Conv2D [here](https://github.com/PINTO0309/openvino2tensorflow/blob/a3313c8a6cfe347f7b886adecbe158d242ff8928/openvino2tensorflow/openvino2tensorflow.py#L345) and used mode='valid' in Conv2D if data.attrib['pads_begin'] contains nonzero values (otherwise didn't change anything), and it solved my problem.

**Comment by PINTO0309** [comment]
I am not sure if it is the same as the fix you gave me, but it looks like the figure below. I still feel a little out of alignment. **`GroupConvolution`** (**`DepthwiseConv2D`**) seems to have the same problem.
![Screenshot 2021-02-03 22:06:56](https://user-images.githubusercontent.com/33194443/106753082-85abda00-666e-11eb-8412-09e0d9454183.png)
