### ISSUE TITLE
openvino2tensorflow.py does not use provided values in weight configuration JSON

### ISSUE THREAD

**Issue by QasimKhan5x** [PINTO0309/openvino2tensorflow#23]
#### 1. OS you are using e.g. Ubuntu 20.04, WIndows10, etc
Windows 10
#### 2. OS Architecture e.g. x86_64, armv7l, aarch64, etc
x64
#### 3. Version of OpenVINO e.g. 2021.2.185, etc
openvino_2021.2.185
#### 4. Version of TensorFlow e.g. v2.4.1, tf-nightly==2.5.0.dev20210128, etc
tensorflow==2.4.1

#### 13. Issue Details
I am trying to convert an OpenVino model for image segmentation into tflite. However, the `Reshape` and `Transpose` layers are not working correctly. In particular, the model that I am using has a `Softmax` layer with `layer_id = 1074` and a Const layer with `layer_id = 1075`, both of which are sending output to layer 1076 as follows:
```
<edge from-layer="1074" from-port="1" to-layer="1076" to-port="0"/>
<edge from-layer="1075" from-port="1" to-layer="1076" to-port="1"/>
<edge from-layer="1076" from-port="2" to-layer="1078" to-port="0"/>
<edge from-layer="1077" from-port="1" to-layer="1078" to-port="1"/>
```
The input and output of Softmax Layer 1074 are shaped as (263169, 151). 

The code for these layers is as follows:
```
<layer id="1074" name="Decoder/softmax/Softmax" type="SoftMax" version="opset1">
	<data axis="1"/>
	<input>
		<port id="0">
			<dim>263169</dim>
			<dim>151</dim>
		</port>
	</input>
	<output>
		<port id="1" precision="FP32">
			<dim>263169</dim>
			<dim>151</dim>
		</port>
	</output>
</layer>
<layer id="1075" name="Decoder/softmax/Reshape_1/Cast_121669_const627_const" type="Const" version="opset1">
	<data element_type="i64" offset="4370080" shape="4" size="32"/>
	<output>
		<port id="1" precision="I64">
			<dim>4</dim>
		</port>
	</output>
</layer>
```

The layer which is receiving output is Reshape layer with `layer_id = 1076`, which is as follows:
```
<layer id="1076" name="Decoder/softmax/Reshape_1" type="Reshape" version="opset1">
	<data special_zero="False"/>
	<input>
		<port id="0">
			<dim>263169</dim>
			<dim>151</dim>
		</port>
		<port id="1">
			<dim>4</dim>
		</port>
	</input>
	<output>
		<port id="2" precision="FP32">
			<dim>1</dim>
			<dim>513</dim>
			<dim>513</dim>
			<dim>151</dim>
		</port>
	</output>
</layer>
```

A Const layer comes after it:
```
<layer id="1077" name="Decoder/softmax/Reshape_1/Transpose/Cast_15806_const" type="Const" version="opset1">
	<data element_type="i64" offset="4370112" shape="4" size="32"/>
	<output>
		<port id="1" precision="I64">
			<dim>4</dim>
		</port>
	</output>
</layer>
```

These two layers are sending output to layer 1078, which is a Transpose layer. Its code is as follows:
```
<layer id="1078" name="Decoder/softmax/Reshape_1/Transpose" type="Transpose" version="opset1">
	<input>
		<port id="0">
			<dim>1</dim>
			<dim>513</dim>
			<dim>513</dim>
			<dim>151</dim>
		</port>
		<port id="1">
			<dim>4</dim>
		</port>
	</input>
	<output>
		<port id="2" precision="FP32">
			<dim>1</dim>
			<dim>151</dim>
			<dim>513</dim>
			<dim>513</dim>
		</port>
	</output>
</layer>
```
 However, the Transpose layer is not receiving the correct input shape. The Reshape layer (1076) should send the output of shape (1, 513, 513, 151) to Transpose (1078) but instead, it is sending output with shape (1, 513, 151, 513).

To produce this issue, I have issued the command:
`python openvino2tensorflow.py --model_path=model.xml --output_no_quant_float32_tflite True --weight_replacement_config weights_config.json`

such that `weights_config.json` is as follows:
```
{
    "format_version": 1,
    "layers": [
		{
            "layer_id": "1077",
            "replace_mode": "direct",
            "values": [
                1,
                513,
                513,
                151
            ]
        }
    ]
}
```

To my understanding, this should overwrite the erroneous behavior of Reshape layer (1076) so that the Transpose layer (1078) receives the correct input shape.

However, I have received the following error:
```
Traceback (most recent call last):
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2216, in transpose
    return transpose_fn(a, perm, name=name)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 11589, in transpose
    x, perm, name=name, ctx=_ctx)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 11609, in transpose_eager_fallback
    _attr_T, (x,) = _execute.args_to_matching_eager([x], ctx, [])
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\eager\execute.py", line 274, in args_to_matching_eager
    t, dtype, preferred_dtype=default_dtype, ctx=ctx)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\profiler\trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\ops.py", line 1540, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\constant_op.py", line 339, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\constant_op.py", line 265, in constant
    allow_broadcast=True)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\constant_op.py", line 276, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\constant_op.py", line 301, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\constant_op.py", line 98, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\engine\keras_tensor.py", line 274, in __array__
    'Cannot convert a symbolic Keras input/output to a numpy array. '
TypeError: Cannot convert a symbolic Keras input/output to a numpy array. This error may indicate that you're trying to pass a symbolic value to a NumPy call, which is not supported. Or, you may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\ops.py", line 1853, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: perm dim 512 is out of range of input rank 4 for '{{node tf.compat.v1.transpose_2/transpose}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32](Placeholder, tf.compat.v1.transpose_2/transpose/perm)' with input shapes: [1,513,151,513], [4] and with computed input tensors: input[1] = <3 512 512 150>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2135, in transpose_v2
    return transpose(a=a, perm=perm, name=name, conjugate=conjugate)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\util\dispatch.py", line 205, in wrapper
    result = dispatch(wrapper, args, kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\util\dispatch.py", line 122, in dispatch
    result = dispatcher.handle(op, args, kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\layers\core.py", line 1450, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 952, in __call__
    input_list)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1091, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\layers\core.py", line 1327, in _call_wrapper
    return self._call_wrapper(*args, **kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\layers\core.py", line 1359, in _call_wrapper
    result = self.function(*args, **kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2216, in transpose
    return transpose_fn(a, perm, name=name)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 11594, in transpose
    "Transpose", x=x, perm=perm, name=name)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\func_graph.py", line 592, in _create_op_internal
    compute_device)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\ops.py", line 3536, in _create_op_internal
    op_def=op_def)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\ops.py", line 2016, in __init__
    control_input_ops, op_def)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\ops.py", line 1856, in _create_c_op
    raise ValueError(str(e))
ValueError: perm dim 512 is out of range of input rank 4 for '{{node tf.compat.v1.transpose_2/transpose}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32](Placeholder, tf.compat.v1.transpose_2/transpose/perm)' with input shapes: [1,513,151,513], [4] and with computed input tensors: input[1] = <3 512 512 150>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\ops.py", line 1853, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: perm dim 512 is out of range of input rank 4 for '{{node tf.transpose/transpose}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32](Placeholder, tf.transpose/transpose/perm)' with input shapes: [1,513,151,513], [4] and with computed input tensors: input[1] = <3 512 512 150>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "openvino2tensorflow.py", line 2382, in <module>
    main()
  File "openvino2tensorflow.py", line 2378, in main
    yolact, weight_replacement_config, debug, debug_layer_number)
  File "openvino2tensorflow.py", line 1069, in convert
    print('res =', tf.transpose(tf_layers_dict[get_tf_edges_from(tf_edges, layer_id, 0)], perm=perm).shape)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\util\dispatch.py", line 205, in wrapper
    result = dispatch(wrapper, args, kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\util\dispatch.py", line 122, in dispatch
    result = dispatcher.handle(op, args, kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\layers\core.py", line 1450, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 952, in __call__
    input_list)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1091, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\layers\core.py", line 1327, in _call_wrapper
    return self._call_wrapper(*args, **kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\keras\layers\core.py", line 1359, in _call_wrapper
    result = self.function(*args, **kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2135, in transpose_v2
    return transpose(a=a, perm=perm, name=name, conjugate=conjugate)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2216, in transpose
    return transpose_fn(a, perm, name=name)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 11594, in transpose
    "Transpose", x=x, perm=perm, name=name)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\func_graph.py", line 592, in _create_op_internal
    compute_device)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\ops.py", line 3536, in _create_op_internal
    op_def=op_def)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\ops.py", line 2016, in __init__
    control_input_ops, op_def)
  File "E:\Anaconda\envs\openvino-vyro\lib\site-packages\tensorflow\python\framework\ops.py", line 1856, in _create_c_op
    raise ValueError(str(e))
ValueError: perm dim 512 is out of range of input rank 4 for '{{node tf.transpose/transpose}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32](Placeholder, tf.transpose/transpose/perm)' with input shapes: [1,513,151,513], [4] and with computed input tensors: input[1] = <3 512 512 150>.
```

Not only is the `Transpose` layer (1078) receiving wrong input but the `perm` parameter of Transpose has been somehow set to <3 512 512 150>. How can I solve this?

**Comment by PINTO0309** [comment]
Please share the xml information **`<layers>`** from layer_id = 1070 to layer_id = 1080. Also, please share **`<edges>`** from to_layer = 1070 to to_layer = 1080. The layer_id of Const used by Softmax is probably "1073".

It would be nice if you could only share the .xml if possible, as my intention is not clear. The .bin is not necessary.

**Comment by QasimKhan5x** [comment]
Ok I am emailing it to you as usual.

**Comment by PINTO0309** [comment]
Try the following.

## 1. Reshape

### 1-1. .xml Reshape Const
```xml
<layer id="1075" name="Decoder/softmax/Reshape_1/Cast_121669_const627_const" type="Const" version="opset1">
	<data element_type="i64" offset="4370080" shape="4" size="32"/>
	<output>
		<port id="1" precision="I64">
			<dim>4</dim>
		</port>
	</output>
</layer>
```
### 1-2. .config Reshape Const
```json
        {
            "layer_id": "1075",
            "replace_mode": "direct",
            "values": [
                1,
                151,
                513,
                513
            ]
        },
```
## Transpose
### 2-1. .xml Reshape Const
```xml
<layer id="1077" name="Decoder/softmax/Reshape_1/Transpose/Cast_15806_const" type="Const" version="opset1">
	<data element_type="i64" offset="4370112" shape="4" size="32"/>
	<output>
		<port id="1" precision="I64">
			<dim>4</dim>
		</port>
	</output>
</layer>
```
### 2-2. .config Reshape Const
```xml
        {
            "layer_id": "1077",
            "replace_mode": "direct",
            "values": [
                0,
                3,
                1,
                2
            ]
        }
```

**Comment by QasimKhan5x** [comment]
Thanks, it worked. But why doesn't it work only with .config Reshape Const since it is just the Reshape layer that is providing the wrong output?

**Comment by PINTO0309** [comment]
As a result of changing the behavior of Reshape, the expected behavior of the subsequent Transpose will also change. You will need to slightly adjust the behavior of the layers after Reshape to maintain the dimensional relationship between the layers. As explained in the previous issue, it is designed to perform conversion operations for NCHW inputs, so fine tuning is required for non-NCHW inputs.

Sorry for the confusion.
