### ISSUE TITLE
openvino convert list index out of range

### ISSUE THREAD

**Issue by FerreJanssen** [PINTO0309/openvino2tensorflow#36]
####  Issue Details
I am following your blog post (https://qiita.com/PINTO/items/ed06e03eb5c007c2e102#6-8-onnx---openvino-ir-conversion) and trying to convert OSnet to tflite. I saw someone else was succesfull in doing [so](https://github.com/google-coral/edgetpu/issues/290) but I get the following error when trying to convert the OpenVINO model to a tensorflow saved_model.
```
openvino2tensorflow --model_path=openvino/osnet_opt.xml  --output_saved_model True

TensorFlow/Keras model building process starts ======================================
Traceback (most recent call last):
  File "/home/ferrejanssen/anaconda3/envs/fastreid/bin/openvino2tensorflow", line 2437, in <module>
    main()
  File "/home/ferrejanssen/anaconda3/envs/fastreid/bin/openvino2tensorflow", line 2433, in main
    yolact, weight_replacement_config, debug, debug_layer_number)
  File "/home/ferrejanssen/anaconda3/envs/fastreid/bin/openvino2tensorflow", line 449, in convert
    if temp.shape[0] == 1 and temp.shape[2] == 1 and temp.shape[3] == 1:
  File "/home/ferrejanssen/anaconda3/envs/fastreid/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 889, in __getitem__
    return self._dims[key].value
IndexError: list index out of range
```

**Comment by BernardinD** [comment]
This has to do with the save function that is used when creating the saved_model. The current script uses `tf.saved_model.save()` when it should use the updated `model.save()`.  The former causes different behavior for different graphs. Some will work while other will get the error when being loaded

**Comment by PINTO0309** [comment]
Please use v1.13.0
```bash
$ xhost +local: && \
  docker run -it --rm \
  -v `pwd`:/home/user/workdir \
  -v /tmp/.X11-unix/:/tmp/.X11-unix:rw \
  --device /dev/video0:/dev/video0:mwr \
  --net=host \
  -e XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
  -e DISPLAY=$DISPLAY \
  --privileged \
  pinto0309/openvino2tensorflow:latest
$ cd workdir

$ pip list | grep openvino2tensorflow
openvino2tensorflow      1.13.0

$ openvino2tensorflow \
--model_path openvino/osnet_opt.xml \
--output_saved_model

TensorFlow/Keras model building process starts ======================================
TensorFlow/Keras model building process complete!
saved_model output started ==========================================================
saved_model output complete!
All the conversion process is finished! =============================================
```
