### ISSUE TITLE
Yolov5 model conversion error, ValueError: axes don't match array

### ISSUE THREAD

**Issue by AlanDecode** [PINTO0309/openvino2tensorflow#38]
#### 1. OS you are using e.g. Ubuntu 20.04, WIndows10, etc

macOS BigSur 11.4

#### 2. OS Architecture e.g. x86_64, armv7l, aarch64, etc

x86_64

#### 3. Version of OpenVINO e.g. 2021.2.185, etc

openvino                 2021.3.0
openvino-dev             2021.3.0

#### 4. Version of TensorFlow e.g. v2.4.1, tf-nightly==2.5.0.dev20210128, etc

tensorflow-cpu           2.3.1

#### 8. Version of ONNX e.g. v1.8.0, etc

onnx                     1.9.0

#### 11. URL of the repository from which the transformed model was taken

https://github.com/ultralytics/yolov5

#### 13. Issue Details

Hi! Thanks for this great tool, it's really handy for people playing with multiple frameworks like me! Here's a problem I ran into today and unfortunately I could not figure it by myself :( . I'll really appreciate it if you can help me on this a little.

I first converted an onnx model from [YOLOv5](https://github.com/ultralytics/yolov5) pre-trained [checkpoint](https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt), then converted it to OpenVINO IR, when I run openvino2tensorflow, bellow error happened:

```
$ openvino2tensorflow \  
  --model_path tmp/yolov5s.xml \
  --model_output_path ./tmp \
  --output_pb
TensorFlow/Keras model building process starts ======================================
Traceback (most recent call last):
  File "/Users/alan/.conda/envs/DL/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1812, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 3 and 76 for '{{node Add_56}} = Add[T=DT_FLOAT](Add_55, Add_56/y)' with input shapes: [1,76,3,2,120], [1,1,76,120,2].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alan/.conda/envs/DL/bin/openvino2tensorflow", line 500, in convert
    tf_layers_dict[layer_id] = tf.math.add(tf_layers_dict[edge_id0], tf_layers_dict[edge_id1])
  File "/Users/alan/.conda/envs/DL/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 357, in add
    "Add", x=x, y=y, name=name)
  File "/Users/alan/.conda/envs/DL/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/Users/alan/.conda/envs/DL/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 593, in _create_op_internal
    compute_device)
  File "/Users/alan/.conda/envs/DL/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3485, in _create_op_internal
    op_def=op_def)
  File "/Users/alan/.conda/envs/DL/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1975, in __init__
    control_input_ops, op_def)
  File "/Users/alan/.conda/envs/DL/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1815, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 3 and 76 for '{{node Add_56}} = Add[T=DT_FLOAT](Add_55, Add_56/y)' with input shapes: [1,76,3,2,120], [1,1,76,120,2].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alan/.conda/envs/DL/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1812, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 3 and 76 for '{{node Add_57}} = Add[T=DT_FLOAT](Add_55, Add_57/y)' with input shapes: [1,76,3,2,120], [1,1,76,120,2].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alan/.conda/envs/DL/bin/openvino2tensorflow", line 506, in convert
    tf_layers_dict[layer_id] = tf.math.add(tf_layers_dict[edge_id0], tf_layers_dict[edge_id1])
  File "/Users/alan/.conda/envs/DL/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 357, in add
    "Add", x=x, y=y, name=name)
  File "/Users/alan/.conda/envs/DL/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 744, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/Users/alan/.conda/envs/DL/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 593, in _create_op_internal
    compute_device)
  File "/Users/alan/.conda/envs/DL/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3485, in _create_op_internal
    op_def=op_def)
  File "/Users/alan/.conda/envs/DL/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1975, in __init__
    control_input_ops, op_def)
  File "/Users/alan/.conda/envs/DL/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1815, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 3 and 76 for '{{node Add_57}} = Add[T=DT_FLOAT](Add_55, Add_57/y)' with input shapes: [1,76,3,2,120], [1,1,76,120,2].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alan/.conda/envs/DL/bin/openvino2tensorflow", line 2898, in <module>
    main()
  File "/Users/alan/.conda/envs/DL/bin/openvino2tensorflow", line 2894, in main
    yolact, restricted_resize_image_mode, weight_replacement_config, debug, debug_layer_number)
  File "/Users/alan/.conda/envs/DL/bin/openvino2tensorflow", line 508, in convert
    tf_layers_dict[layer_id] = tf.math.add(tf_layers_dict[edge_id0], tf_layers_dict[edge_id1].transpose(0,2,3,1))
ValueError: axes don't match array
```

 I have no idea why `Add_56` takes such inputs in the error message, as the .xml looks like this:

```
<layer id="59" name="Add_56" type="Add" version="opset1">
	<data auto_broadcast="numpy"/>
	<input>
		<port id="0">
			<dim>1</dim>
			<dim>32</dim>
			<dim>152</dim>
			<dim>240</dim>
		</port>
		<port id="1">
			<dim>1</dim>
			<dim>32</dim>
			<dim>152</dim>
			<dim>240</dim>
		</port>
	</input>
	<output>
		<port id="2" names="183" precision="FP32">
			<dim>1</dim>
			<dim>32</dim>
			<dim>152</dim>
			<dim>240</dim>
		</port>
	</output>
</layer>
```

Mentioned model files can be found here: https://static.imalan.cn/share/yolov5s.zip, thanks for your help in advance!

**Comment by lp6m** [comment]
I met the same problem, and fix the problem.
The problem is conversion rule of  5-dim `Transpose` layer. The input and output shape of transpose layer is like:
```
input (1, 80, 80, 3, 85)
output (1, 80, 3, 85, 80)
```
And `VariadicSplit` layer conversion also have the problem. The split axis is wrong. In yolov5s, valiadic split is like:
```
input (1, 80, 80, 3, 85)
output (1, 80, 80, 3, 81), (1, 80, 80, 3, 2), (1, 80, 80, 3, 2)
```
so the split axis is 4. But `openvino2tensorflow` determines wrong axis.

I modified the code as a hotfix, and yolov5s model can be converted successfully.  (I also confirmed that the inference result is correct.)

https://github.com/lp6m/openvino2tensorflow/commit/558c0ae510ce2a9732b816c643fd29c574d418c3
My hotfix isn't generic, so it's inappropriate for other models.

**Comment by PINTO0309** [comment]
You can modify the fixed parameters of a layer externally without having to modify the program.
https://github.com/PINTO0309/openvino2tensorflow#6-7-replace-weights-or-constant-values-in-const-op

**Comment by AlanDecode** [comment]
Thanks for the instruction! Although I've wrote my own conversion script dedicated for YoloV5, I will still give your way it a try!

**Comment by AlexisPapaioannou** [comment]
Is there any generic way in order to make the conversion?
